### PR TITLE
Added workflow file for building when anything is pushed

### PR DESCRIPTION
**Pull request by Flurb**

### CODE REVIEW

**Review by LRBH10 — APPROVED** [review]
So quarkus 👍 
We will think how we can add native compilation

**Review by Sander3003 — APPROVED** [review]

**Comment by Sander3003** [comment]
@LRBH10 What do you mean by _native compilation_?

**Comment by Flurb** [comment]
Native compilation means we do not need a Java Runtime for running the Quarkus Microservice.
And not using a Java Runtime, means huge decrease of resources and startup times for example 👍 

If we compile it for example with GraalVM (which I expect we are using), we can create a native executable.

**Comment by Sander3003** [comment]
Looks good, it can help to run the software to Windows/Linux desktops more easy

**Comment by Flurb** [comment]
> Looks good, it can help to run the software to Windows/Linux desktops more easy

And you want the Quarkus benefits stated on their website (memory usage & response times):
https://quarkus.io/

**Pull request merged**
