### PR TITLE
feat: REUSE GitHub workflow

### PR DESCRIPTION
**Pull request by nicorikken**
Inclusion of the REUSE license check tool (https://reuse.software/).
More details on this GitHub Action can be found in the GitHub Marketplace:
https://github.com/marketplace/actions/reuse-compliance-check

The result of the scan is eligable for a badge, which can be included at a later
stage.

Signed-off-by: Nico Rikken <nico.rikken@alliander.com>

### CODE REVIEW

**Comment by nicorikken** [comment]
At the moment the REUSE check is failing, as expected. I'll create a separate PR with proper copyright and license information so this should work after rebasing.

**Comment by Flurb** [comment]
Looks great, good to have a default Github Action for Reuse :)

Commits aren't passing the DCO check, all commits should have a signoff flag :)

Using the --signoff flag with each git commit resolves this!

Maybe a second step would be not only detecting if there is no license information, but also auto injecting license information

**Comment by Flurb** [comment]
Nice!

**Review by Flurb — COMMENTED** [review]
Looks good!

**Pull request merged**
